python exceptions using try and catch/exceptions